name: Nightly Build

on:
  # 手动触发
  workflow_dispatch:

  # 定时触发 (UTC 时间 20:00，相当于北京时间次日 04:00)
  schedule:
    - cron: '0 20 * * *'

jobs:
  nightly-build:
    name: Nightly Build
    runs-on: ubuntu-latest

    steps:
      # 1. 获取当前日期和时间（使用 Asia/Shanghai 时区）
      - name: Get current date
        id: date
        run: |
          BJ_DATE=$(TZ=Asia/Shanghai date '+%Y-%m-%d')
          BJ_TIME=$(TZ=Asia/Shanghai date '+%H:%M:%S')

          echo "NB_LOCAL_DATE=$BJ_DATE" >> $GITHUB_ENV
          echo "NB_LOCAL_TIME=$BJ_TIME" >> $GITHUB_ENV
          # 如果要让 Tag 名也用 patch- 前缀，可以改这里
          echo "NB_TAG=patch-$BJ_DATE" >> $GITHUB_ENV

      # 2. 检出本仓库代码
      - name: Check out
        uses: actions/checkout@v3

      # 3. 下载另一个仓库最新 Release 中的 nightly-*.7z
      - name: Download latest release from GTNH-UCN/Translation-of-GTNH
        uses: robinraju/release-downloader@v1
        with:
          repository: 'GTNH-UCN/Translation-of-GTNH'
          latest: true
          fileName: 'nightly-*.7z'
          out-file-path: 'temp'
          token: ${{ secrets.GITHUB_TOKEN }}

      # 4. 解压 nightly-*.7z 到 temp/extracted
      - name: Extract translation
        uses: edgarrc/action-7z@v1
        with:
          args: 7z x -y temp/nightly-*.7z -otemp/extracted

      # 5. 合并到本仓库（如需排除可用 --exclude）
      - name: Merge downloaded content to this repo
        run: |
          rsync -av temp/extracted/ ./

      # 6. 打包成 7z（文件名改为 patch-日期.7z）
      - name: Zip Output
        uses: edgarrc/action-7z@v1
        with:
          # 注意，这里改为 patch-$NB_LOCAL_DATE.7z
          args: 7z a -t7z -mx=9 ./assets/patch-$NB_LOCAL_DATE.7z ./ \
            -x!GTNH介绍.txt \
            -x!看我.md \
            -x!.github

      # 7. 推送 tag 到远程
      - name: Push tag
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git checkout --orphan temp
          git reset HEAD -- .
          git commit --allow-empty -m "Nightly Build $NB_LOCAL_DATE $NB_LOCAL_TIME"

          git tag $NB_TAG
          git push --delete origin $NB_TAG || true
          git push origin $NB_TAG

      # 8. 发布 Release
      - name: Release Nightly Build
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $NB_TAG
          name: 每日构建 - $NB_LOCAL_DATE
          body: |
            请阅读主页 ReadMe 以获知详细用法

            自动构建于 $NB_LOCAL_DATE $NB_LOCAL_TIME
          # 同样需要把上传的文件名改为 patch-$NB_LOCAL_DATE.7z
          files: |
            ./assets/patch-$NB_LOCAL_DATE.7z
